### ISSUE TITLE
filesystem.NewStorage() is crashed on v4

### ISSUE THREAD

**Issue by idanko** [src-d/go-git#704]
Hello, I'm user of golang 1.9.2 on my macbook. Recently, I have installed go-git package using 'go get -u gopkg.in/src-d/go-git.v4/...' (as suggested on readme).
The issue raised, when I was trying to initialize new filesystem storage:
`storage, err := filesystem.NewStorage(fs)` with following error:
```
# command-line-arguments
./main.go:19:39: cannot use fs (type "gopkg.in/src-d/go-billy.v4".Filesystem) as type "gopkg.in/src-d/go-billy.v3".Filesystem in argument to filesystem.NewStorage:
	"gopkg.in/src-d/go-billy.v4".Filesystem does not implement "gopkg.in/src-d/go-billy.v3".Filesystem (wrong type for Chroot method)
		have Chroot(string) ("gopkg.in/src-d/go-billy.v4".Filesystem, error)
		want Chroot(string) ("gopkg.in/src-d/go-billy.v3".Filesystem, error)
./main.go:22:23: cannot use fs (type "gopkg.in/src-d/go-billy.v4".Filesystem) as type "gopkg.in/src-d/go-billy.v3".Filesystem in argument to git.Open:
	"gopkg.in/src-d/go-billy.v4".Filesystem does not implement "gopkg.in/src-d/go-billy.v3".Filesystem (wrong type for Chroot method)
		have Chroot(string) ("gopkg.in/src-d/go-billy.v4".Filesystem, error)
		want Chroot(string) ("gopkg.in/src-d/go-billy.v3".Filesystem, error)

```
Here is whole code:
```
package main

import (
	"log"

	"gopkg.in/src-d/go-billy.v4/osfs"
	git "gopkg.in/src-d/go-git.v4"
	"gopkg.in/src-d/go-git.v4/storage/filesystem"
)

func must(err error) {
	if err != nil {
		log.Fatal(err)
	}
}

func main() {
	fs := osfs.New("fake_repo_path")
	storage, err := filesystem.NewStorage(fs)
	must(err)

	repo, err := git.Open(storage, fs)
	must(err)
	log.Println(repo)
}
```
Maybe I do something wrong? But at least the error message is not related to usage scope.
PS. It was a clean package installation (I have never installed it before).

**Comment by mcuadros** [comment]
Should be working on the new v4.0.0 release

**Comment by idanko** [comment]
Fixed. Just required completely reinstall:
```
rm -rf $GOPATH/src/gopkg.in/src-d
go get -u gopkg.in/src-d/go-git.v4/...
```
